"""Writing the suite out.

Generated code is read far more often than generated code is run, and this
particular generated code arrives in somebody's repository uninvited. So every
file explains itself: which metrics it holds, what each one catches, why it was
chosen for this target, and what a failure would mean. The explanation is not a
courtesy -- a suite whose reasoning is invisible gets deleted the first time it
disagrees with its owner, and it will disagree.

Three things are deliberately *not* generated.

**The metric implementations.** Faithfulness, answer relevancy and the rest are
already correct in DeepEval, and reimplementing them would be a worse version of
somebody else's solved problem. The emitted files call it.

**The application entry point.** `harness.py` imports the function the scanner
found and adapts it. Guessing an interface tends to produce a suite that runs
against nothing and reports a confident zero, so where the shape is unclear the
harness raises with a message naming the file and line to fix.

**Any answer a human owes.** See `goldens`.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass
from pathlib import Path

from livingeval.generate.goldens import GoldenSet
from livingeval.plan.planner import Pipeline, Plan
from livingeval.plan.taxonomy import Mechanism, Method, Metric, Reference

__all__ = ["Emission", "emit"]

BANNER = "# Generated by livingeval. Edit freely -- regeneration merges, never clobbers."


@dataclass
class Emission:
    """What was written, for the CLI to report."""

    files: list[Path]
    goldens: list[Path]
    runnable: int
    blocked: int


def _wrap(text: str, width: int = 76, indent: str = "",
          hang: str | None = None) -> str:
    """Fill, with continuation lines indented under the first.

    `hang` defaults to `indent`; a deeper one gives a hanging indent, so a
    wrapped bullet stays visibly part of its bullet rather than colliding with
    the left margin and reading as a new item.
    """
    return textwrap.fill(" ".join(text.split()), width,
                         initial_indent=indent,
                         subsequent_indent=indent if hang is None else hang)


def _why_block(pipeline: Pipeline) -> str:
    """The docstring that tells the reader why this file exists."""
    lines = [f"{pipeline.target.title()} evals: {pipeline.risk.value}.", ""]
    lines.append(_wrap(
        {"component": "This checks one piece in isolation. Passing here does "
                      "not mean the pipeline works -- see the workflow evals.",
         "workflow": "This checks the composition. Components that each pass "
                     "on their own still compose into a broken pipeline: the "
                     "classic case is a retriever that returns the right "
                     "document at rank five while the generator answers from "
                     "rank one. Neither component misbehaved.",
         "application": "This checks the whole thing end to end, including the "
                        "properties that make a correct system undeployable.",
         }[pipeline.level.value]))
    lines += ["", "Why these metrics:", ""]
    for metric in pipeline.metrics:
        lines.append(_wrap(f"{metric.name} -- {metric.catches}",
                           indent="  ", hang="      "))
        detail = []
        if metric.reference is Reference.BASED:
            detail.append("needs a reference answer, so it starts blocked")
        if metric.mechanism is Mechanism.JUDGEMENT:
            detail.append("scored holistically, so it uses G-Eval rather than a "
                          "bare judge: a one-line criterion gets re-interpreted "
                          "on every call and an integer score flips between "
                          "adjacent digits")
        if metric.triangulates:
            detail.append("read it beside " + ", ".join(metric.triangulates))
        if not metric.higher_is_better:
            detail.append("lower is better")
        for item in detail:
            lines.append(_wrap(f"({item})", indent="      ", hang="       "))
        lines.append("")
    if pipeline.rationale:
        lines.append("Why this target was classified the way it was:")
        lines += [_wrap(f"- {r}", indent="  ", hang="    ")
                  for r in pipeline.rationale]
    return "\n".join(lines).rstrip()


def _metric_expr(metric: Metric, judge: str) -> str:
    """The DeepEval construction for one metric."""
    if metric.mechanism is Mechanism.JUDGEMENT and metric.method is Method.MODEL_GRADED:
        criterion = (metric.geval_criterion or metric.catches).replace('"', "'")
        params = ["LLMTestCaseParams.INPUT", "LLMTestCaseParams.ACTUAL_OUTPUT"]
        if metric.reference is Reference.BASED:
            params.append("LLMTestCaseParams.EXPECTED_OUTPUT")
        return (
            f'GEval(\n'
            f'        name="{metric.name}",\n'
            f'        criteria=(\n{_quoted(criterion, 12)}\n        ),\n'
            f'        evaluation_params=[{", ".join(params)}],\n'
            f'        model=JUDGE,\n'
            f'        threshold=THRESHOLDS["{metric.key}"],\n'
            f'    )')

    builtin = {
        "faithfulness": "FaithfulnessMetric",
        "answer_relevancy": "AnswerRelevancyMetric",
        "contextual_relevance": "ContextualRelevancyMetric",
        "contextual_recall": "ContextualRecallMetric",
        "contextual_precision": "ContextualPrecisionMetric",
        "toxicity": "ToxicityMetric",
        "pii_leakage": "PIILeakageMetric",
    }.get(metric.name)
    if builtin:
        return (f'{builtin}(threshold=THRESHOLDS["{metric.key}"], '
                f'model=JUDGE, include_reason=True)')
    # Programmatic metrics have no DeepEval equivalent; the harness measures them.
    return f'local_metric("{metric.key}")'


def _quoted(text: str, indent: int) -> str:
    pad = " " * indent
    return "\n".join(f'{pad}"{line} "' for line in textwrap.wrap(text, 66))


def _eval_file(pipeline: Pipeline, judge: str) -> str:
    needs_geval = any(m.mechanism is Mechanism.JUDGEMENT and
                      m.method is Method.MODEL_GRADED for m in pipeline.metrics)
    builtins = sorted({
        {"faithfulness": "FaithfulnessMetric",
         "answer_relevancy": "AnswerRelevancyMetric",
         "contextual_relevance": "ContextualRelevancyMetric",
         "contextual_recall": "ContextualRecallMetric",
         "contextual_precision": "ContextualPrecisionMetric",
         "toxicity": "ToxicityMetric",
         "pii_leakage": "PIILeakageMetric"}[m.name]
        for m in pipeline.metrics
        if m.name in {"faithfulness", "answer_relevancy", "contextual_relevance",
                      "contextual_recall", "contextual_precision", "toxicity",
                      "pii_leakage"}})

    imports = [BANNER, '"""', _why_block(pipeline), '"""', "",
               "from livingeval_evals.harness import (",
               "    JUDGE, THRESHOLDS, load_cases, local_metric, run_pipeline,",
               ")", ""]
    if builtins:
        imports.append("from deepeval.metrics import " + ", ".join(builtins))
    if needs_geval:
        imports += ["from deepeval.metrics import GEval",
                    "from deepeval.test_case import LLMTestCaseParams"]
    imports.append("")

    metric_lines = ",\n    ".join(_metric_expr(m, judge) for m in pipeline.metrics)
    body = f'''
NAME = "{pipeline.slug}"

# Metrics for this target. Each is explained in the module docstring above.
METRICS = [
    {metric_lines},
]

# Golden sets, keyed by the metric that consumes them. Sets marked incomplete in
# their JSON are skipped with a warning rather than scored against empty answers.
CASES = load_cases({[m.key for m in pipeline.metrics]!r})


def run() -> dict:
    """Score this pipeline. Returns {{metric_key: value}} for the suite runner."""
    return run_pipeline(NAME, METRICS, CASES)


if __name__ == "__main__":
    import json
    print(json.dumps(run(), indent=2))
'''
    return "\n".join(imports) + body


# ---------------------------------------------------------------------------
# harness
# ---------------------------------------------------------------------------

HARNESS = '''{banner}
"""Shared plumbing: one place that knows how to call your application.

Every generated eval imports from here, so this is the only file that has to
change when your entry point moves. It was written against what the scanner
found; if the call below is wrong, fix it here once.

Discovered entry point{plural}:
{discovered}
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

HERE = Path(__file__).parent
GOLDENS = HERE / "goldens"

# The judge. Every model-graded metric uses this one model, so that scores are
# comparable across the suite and a judge upgrade is a single edit.
JUDGE = os.environ.get("LIVINGEVAL_JUDGE", "{judge}")

# Per-metric pass marks. These are starting points, not measurements: run
# `livingeval baseline` to replace them with values taken from your own system.
THRESHOLDS = {thresholds}


def load_cases(metric_keys: list[str]) -> dict:
    """Golden sets for these metrics. Incomplete sets are reported, not scored."""
    out = {{}}
    for key in metric_keys:
        path = GOLDENS / (key.replace(".", "_") + ".json")
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        if not data.get("complete", False):
            print(f"  ~ {{key}}: golden set incomplete, skipping "
                  f"({{len(data['cases'])}} cases awaiting answers)")
            continue
        out[key] = data["cases"]
    return out


{target}


def local_metric(key: str):
    """Placeholder for metrics measured by the harness rather than by a judge --
    latency, cost, schema validity. `run_pipeline` handles them directly."""
    return {{"__local__": key}}


def run_pipeline(name: str, metrics: list, cases: dict) -> dict:
    """Score one pipeline and return {{metric_key: value}}.

    Local metrics are measured here; DeepEval metrics are delegated. Timings are
    collected for every call regardless, because operational numbers are free
    once you are already running the suite.
    """
    from deepeval import evaluate
    from deepeval.test_case import LLMTestCase

    results: dict[str, float] = {{}}
    latencies: list[float] = []

    for key, rows in cases.items():
        test_cases = []
        for row in rows:
            started = time.perf_counter()
            output = call_app(row["input"])
            latencies.append(time.perf_counter() - started)
            test_cases.append(LLMTestCase(
                input=row["input"],
                actual_output=output.get("answer", ""),
                retrieval_context=output.get("context"),
                expected_output=row.get("expected"),
            ))
        scored = [m for m in metrics if not isinstance(m, dict)]
        if test_cases and scored:
            report = evaluate(test_cases=test_cases, metrics=scored)
            for metric_result in getattr(report, "test_results", []):
                for data in getattr(metric_result, "metrics_data", []):
                    results.setdefault(data.name, []).append(data.score or 0.0)

    aggregated = {{k: sum(v) / len(v) for k, v in results.items() if v}}
    if latencies:
        ordered = sorted(latencies)
        aggregated["application.latency_p95"] = ordered[int(len(ordered) * 0.95) - 1]
    return aggregated
'''

TARGET_KNOWN = '''def call_app(question: str) -> dict:
    """Call the application under test.

    Returns {{"answer": str, "context": list[str] | None}}. Context is what the
    grounding metrics score against; returning None for it makes faithfulness
    and contextual relevance unmeasurable, so wire it up if you have it.
    """
    from {module} import {function}

    answer = {function}({call_args})
    if isinstance(answer, dict):
        return {{"answer": answer.get("answer", ""), "context": answer.get("context")}}
    return {{"answer": str(answer), "context": None}}
'''

TARGET_UNKNOWN = '''def call_app(question: str) -> dict:
    """Call the application under test.

    The scanner could not work out a safe way to invoke your code, so this is
    yours to write. Returning a fake value here would produce a suite that runs
    green against nothing, which is worse than one that refuses to run.

    Return {{"answer": str, "context": list[str] | None}}.
    """
    raise NotImplementedError(
        "Wire livingeval to your application: edit call_app() in this file. "
        "The scanner found these entry points:\\n{hints}"
    )
'''


def _harness(plan: Plan, judge: str) -> str:
    sites = plan.sites
    discovered = "\n".join(
        f"  {s.path}:{s.line}  {s.function}()  [{s.archetype}]" for s in sites
    ) or "  (none)"

    primary = next((s for s in sites if s.evidence.retrieval), sites[0] if sites else None)
    if primary and primary.function not in {"<module>", "__init__"}:
        module = ".".join(primary.path.with_suffix("").parts).lstrip(".")
        target = TARGET_KNOWN.format(module=module, function=primary.function,
                                     call_args="question")
    else:
        hints = "\\n".join(f"  {s.path}:{s.line} {s.function}()" for s in sites)
        target = TARGET_UNKNOWN.format(hints=hints or "  (none found)")

    thresholds = "{\n" + "".join(
        f'    "{m.key}": {0.3 if not m.higher_is_better else 0.7},\n'
        for p in plan.pipelines for m in p.metrics
    ) + "}"

    return HARNESS.format(
        banner=BANNER, judge=judge, thresholds=thresholds, target=target,
        discovered=discovered, plural="s" if len(sites) != 1 else "")


# ---------------------------------------------------------------------------
# registry, runner, explanation
# ---------------------------------------------------------------------------

REGISTRY = '''{banner}
"""Per-metric direction and noise tolerance.

Regression testing needs both. Direction, because a drop in toxicity is an
improvement and a drop in faithfulness is not -- getting this backwards reports
every safety fix as a regression. Noise tolerance, because these scores are
produced by a probabilistic judge and move by a point or two between identical
runs.

The tolerances below are estimates. `livingeval baseline` runs the suite
repeatedly against an unchanged system and replaces them with the spread it
actually measures, which is the only honest source for this number.

livingeval's gate does not stop at the tolerance -- it runs a paired test and
reports a p-value, and separately asks whether the suite had the power to detect
the regression at all. The tolerance here is what the plain comparison uses.
"""

REGISTRY = {registry}
'''

RUNNER = '''{banner}
"""Run every eval and write one result file.

First run writes `baseline.json`. Subsequent runs write `candidate.json`, which
`livingeval gate` compares against the baseline.

    python -m livingeval_evals.run_suite            # run everything
    python -m livingeval_evals.run_suite --only safety
"""

from __future__ import annotations

import argparse
import importlib
import json
import time
from pathlib import Path

HERE = Path(__file__).parent
PIPELINES = {pipelines!r}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", help="substring filter over pipeline names")
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    selected = [p for p in PIPELINES if not args.only or args.only in p]
    results, started = {{}}, time.time()
    for name in selected:
        print(f"-> {{name}}")
        module = importlib.import_module(f"livingeval_evals.{{name}}")
        results.update(module.run())

    out = args.out or (HERE / ("baseline.json" if not (HERE / "baseline.json").exists()
                               else "candidate.json"))
    out.write_text(json.dumps({{
        "metrics": results,
        "pipelines": selected,
        "seconds": round(time.time() - started, 1),
    }}, indent=2), encoding="utf-8")
    print(f"\\nwrote {{out.name}}  ({{len(results)}} metrics, "
          f"{{time.time() - started:.0f}}s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _explanation(plan: Plan, goldens: dict[str, GoldenSet]) -> str:
    lines = [
        "# Why this suite looks like this", "",
        plan.summary(), "",
        "Generated by `livingeval init`. Every choice below is explained, because "
        "you should be able to disagree with any of them.", "",
        "## What was found", "",
        "| file | line | function | classified as | confidence |",
        "|---|---|---|---|---|",
    ]
    for site in plan.sites:
        lines.append(f"| `{site.path}` | {site.line} | `{site.function}()` | "
                     f"{site.archetype} | {site.confidence:.0%} |")
    lines += ["", "The classification decides which metrics apply, so it is worth "
                  "checking. Reasons given:", ""]
    for site in plan.sites:
        lines.append(f"- **`{site.function}()`** — " + "; ".join(site.rationale))

    lines += ["", "## The pipelines", ""]
    for pipeline in plan.pipelines:
        lines += [f"### `{pipeline.slug}`", "",
                  f"*{pipeline.level.value} level, {pipeline.risk.value} risk.*", "",
                  "| metric | catches | needs |", "|---|---|---|"]
        for metric in pipeline.metrics:
            needs = ("a reference answer from you" if metric.reference is Reference.BASED
                     else "nothing — runs now")
            lines.append(f"| `{metric.name}` | {metric.catches} | {needs} |")
        lines.append("")

    lines += ["## The datasets", ""]
    for key, golden in sorted(goldens.items()):
        state = "complete" if golden.complete else "**awaiting your answers**"
        lines += [f"### `{key}` — {state}", "", golden.why, ""]

    lines += [
        "## What livingeval adds once this is running", "",
        "The suite above tells you whether your scores changed. Three questions it "
        "cannot answer on its own, and which `livingeval gate` does:", "",
        "- **Is the change real?** A paired test with a p-value, rather than "
        "comparing against a hand-picked noise threshold.",
        "- **Could this suite have caught the regression?** Detection power, "
        "simulated against a named regression and reported with its false-alarm rate.",
        "- **Does the suite still represent your traffic?** Coverage — the share of "
        "today's traffic sitting near something the suite contains.", "",
        "That last one is why the gate is three-valued. `PASS`, `FAIL`, and `BLIND`: "
        "\"no regression detected, and this suite could not have detected one\" is a "
        "different claim from \"no regression\".",
    ]
    return "\n".join(lines) + "\n"


def emit(plan: Plan, goldens: dict[str, GoldenSet], root: Path,
         judge: str = "gpt-4o-mini") -> Emission:
    """Write the whole suite under `root/livingeval_evals`.

    A package rather than a loose directory, because `run_suite` imports the
    eval modules by name and a plain folder makes that depend on the working
    directory.
    """
    package = root / "livingeval_evals"
    package.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def put(name: str, text: str) -> None:
        path = package / name
        path.write_text(text, encoding="utf-8")
        written.append(path)

    put("__init__.py", f'{BANNER}\n"""Generated eval suite. See WHY.md."""\n')
    put("harness.py", _harness(plan, judge))

    for pipeline in plan.pipelines:
        put(f"{pipeline.slug}.py", _eval_file(pipeline, judge))

    registry = {
        m.key: {"direction": "higher" if m.higher_is_better else "lower",
                "noise": m.noise_hint, "risk": m.risk.value,
                "catches": m.catches}
        for p in plan.pipelines for m in p.metrics
    }
    put("metric_registry.py", REGISTRY.format(
        banner=BANNER, registry=_pretty(registry)))
    put("run_suite.py", RUNNER.format(
        banner=BANNER, pipelines=[p.slug for p in plan.pipelines]))
    put("WHY.md", _explanation(plan, goldens))

    from livingeval.generate.goldens import write as write_goldens
    golden_paths = write_goldens(goldens, package / "goldens")

    return Emission(
        files=written, goldens=golden_paths,
        runnable=plan.runnable_count, blocked=plan.blocked_count)


def _pretty(mapping: dict) -> str:
    import json
    return json.dumps(mapping, indent=4).replace(": true", ": True").replace(
        ": false", ": False").replace(": null", ": None")
