"""Writing the suite out.

Generated code is read far more often than generated code is run, and this
particular generated code arrives in somebody's repository uninvited. So every
file explains itself: which metrics it holds, what each one catches, why it was
chosen for this target, and what a failure would mean. The explanation is not a
courtesy -- a suite whose reasoning is invisible gets deleted the first time it
disagrees with its owner, and it will disagree.

Three things are deliberately *not* generated.

**The metric implementations.** Faithfulness, answer relevancy and the rest are
already correct in DeepEval, and reimplementing them would be a worse version of
somebody else's solved problem. The emitted files call it.

**The application entry point.** `harness.py` imports the function the scanner
found and adapts it. Guessing an interface tends to produce a suite that runs
against nothing and reports a confident zero, so where the shape is unclear the
harness raises with a message naming the file and line to fix.

**Any answer a human owes.** See `goldens`.
"""

from __future__ import annotations

import textwrap
import time
from dataclasses import dataclass, field
from pathlib import Path

from livingeval.generate.goldens import GoldenSet, write_goldens_preserving
from livingeval.manifest import FileRecord, Manifest, SiteRecord, digest, site_digest
from livingeval.plan.planner import Pipeline, Plan
from livingeval.plan.taxonomy import Mechanism, Method, Metric, Reference

__all__ = ["Emission", "emit"]

BANNER = "# Generated by livingeval. Edit freely -- regeneration merges, never clobbers."


@dataclass
class Emission:
    """What was written, for the CLI to report."""

    files: list[Path]
    goldens: list[Path]
    runnable: int
    blocked: int
    preserved: dict[str, int] = field(default_factory=dict)
    skipped: list[str] = field(default_factory=list)


def _wrap(text: str, width: int = 76, indent: str = "",
          hang: str | None = None) -> str:
    """Fill, with continuation lines indented under the first.

    `hang` defaults to `indent`; a deeper one gives a hanging indent, so a
    wrapped bullet stays visibly part of its bullet rather than colliding with
    the left margin and reading as a new item.
    """
    return textwrap.fill(" ".join(text.split()), width,
                         initial_indent=indent,
                         subsequent_indent=indent if hang is None else hang)


def _why_block(pipeline: Pipeline) -> str:
    """The docstring that tells the reader why this file exists."""
    lines = [f"{pipeline.target.title()} evals: {pipeline.risk.value}.", ""]
    lines.append(_wrap(
        {"component": "This checks one piece in isolation. Passing here does "
                      "not mean the pipeline works -- see the workflow evals.",
         "workflow": "This checks the composition. Components that each pass "
                     "on their own still compose into a broken pipeline: the "
                     "classic case is a retriever that returns the right "
                     "document at rank five while the generator answers from "
                     "rank one. Neither component misbehaved.",
         "application": "This checks the whole thing end to end, including the "
                        "properties that make a correct system undeployable.",
         }[pipeline.level.value]))
    lines += ["", "Why these metrics:", ""]
    for metric in pipeline.metrics:
        lines.append(_wrap(f"{metric.name} -- {metric.catches}",
                           indent="  ", hang="      "))
        detail = []
        if metric.reference is Reference.BASED:
            detail.append("needs a reference answer, so it starts blocked")
        if metric.mechanism is Mechanism.JUDGEMENT:
            detail.append("scored holistically, so it uses G-Eval rather than a "
                          "bare judge: a one-line criterion gets re-interpreted "
                          "on every call and an integer score flips between "
                          "adjacent digits")
        if metric.triangulates:
            detail.append("read it beside " + ", ".join(metric.triangulates))
        if not metric.higher_is_better:
            detail.append("lower is better")
        for item in detail:
            lines.append(_wrap(f"({item})", indent="      ", hang="       "))
        lines.append("")
    if pipeline.rationale:
        lines.append("Why this target was classified the way it was:")
        lines += [_wrap(f"- {r}", indent="  ", hang="    ")
                  for r in pipeline.rationale]
    return "\n".join(lines).rstrip()


def _metric_expr(metric: Metric, judge: str) -> str:
    """The DeepEval construction for one metric."""
    if metric.mechanism is Mechanism.JUDGEMENT and metric.method is Method.MODEL_GRADED:
        criterion = (metric.geval_criterion or metric.catches).replace('"', "'")
        params = ["LLMTestCaseParams.INPUT", "LLMTestCaseParams.ACTUAL_OUTPUT"]
        if metric.reference is Reference.BASED:
            params.append("LLMTestCaseParams.EXPECTED_OUTPUT")
        return (
            f'GEval(\n'
            f'        name="{metric.name}",\n'
            f'        criteria=(\n{_quoted(criterion, 12)}\n        ),\n'
            f'        evaluation_params=[{", ".join(params)}],\n'
            f'        model=JUDGE,\n'
            f'        threshold=THRESHOLDS["{metric.key}"],\n'
            f'    )')

    builtin = {
        "faithfulness": "FaithfulnessMetric",
        "answer_relevancy": "AnswerRelevancyMetric",
        "contextual_relevance": "ContextualRelevancyMetric",
        "contextual_recall": "ContextualRecallMetric",
        "contextual_precision": "ContextualPrecisionMetric",
        "toxicity": "ToxicityMetric",
        "pii_leakage": "PIILeakageMetric",
    }.get(metric.name)
    if builtin:
        return (f'{builtin}(threshold=THRESHOLDS["{metric.key}"], '
                f'model=JUDGE, include_reason=True)')
    # Programmatic metrics have no DeepEval equivalent; the harness measures them.
    return f'local_metric("{metric.key}")'


def _quoted(text: str, indent: int) -> str:
    pad = " " * indent
    return "\n".join(f'{pad}"{line} "' for line in textwrap.wrap(text, 66))


def _eval_file(pipeline: Pipeline, judge: str) -> str:
    needs_geval = any(m.mechanism is Mechanism.JUDGEMENT and
                      m.method is Method.MODEL_GRADED for m in pipeline.metrics)
    builtins = sorted({
        {"faithfulness": "FaithfulnessMetric",
         "answer_relevancy": "AnswerRelevancyMetric",
         "contextual_relevance": "ContextualRelevancyMetric",
         "contextual_recall": "ContextualRecallMetric",
         "contextual_precision": "ContextualPrecisionMetric",
         "toxicity": "ToxicityMetric",
         "pii_leakage": "PIILeakageMetric"}[m.name]
        for m in pipeline.metrics
        if m.name in {"faithfulness", "answer_relevancy", "contextual_relevance",
                      "contextual_recall", "contextual_precision", "toxicity",
                      "pii_leakage"}})

    imports = [BANNER, '"""', _why_block(pipeline), '"""', "",
               "from livingeval_evals.harness import (",
               "    JUDGE, THRESHOLDS, load_cases, local_metric, run_pipeline,",
               ")", ""]
    if builtins:
        imports.append("from deepeval.metrics import " + ", ".join(builtins))
    if needs_geval:
        imports += ["from deepeval.metrics import GEval",
                    "from deepeval.test_case import LLMTestCaseParams"]
    imports.append("")

    # (registry key, metric). Paired rather than listed, for two reasons a live
    # run made obvious: DeepEval labels results with its own display name
    # ("PII Leakage", "toxicity [GEval]"), which never matches a registry key
    # and leaves the gate with nothing to compare; and each metric has to be
    # scored against its own dataset, or injection probes get judged for
    # toxicity and the number means nothing.
    metric_lines = ",\n    ".join(
        f'("{m.key}", {_metric_expr(m, judge)})' for m in pipeline.metrics)
    body = f'''
NAME = "{pipeline.slug}"

# (registry key, metric). Paired rather than listed, for two reasons the live
# run made obvious: DeepEval labels results with its own display name
# ("PII Leakage", "toxicity [GEval]"), which never matches a registry key and
# leaves the gate with nothing to compare; and each metric must be scored
# against its own dataset, or injection probes get judged for toxicity and the
# score means nothing.
METRICS = [
    {metric_lines},
]

# Golden sets, keyed by the metric that consumes them. Sets marked incomplete in
# their JSON are skipped with a warning rather than scored against empty answers.
CASES = load_cases({[m.key for m in pipeline.metrics]!r})


def run() -> dict:
    """Score this pipeline. See `harness.run_pipeline` for the shape."""
    return run_pipeline(NAME, METRICS, CASES)


if __name__ == "__main__":
    import json
    print(json.dumps(run(), indent=2))
'''
    return "\n".join(imports) + body


# Metrics the generated harness cannot measure from what `call_app` returns by
# default, and the one line of instrumentation that would fix each. Read by the
# harness at run time and by WHY.md before anything has run, so a document
# cannot promise a metric the suite will not produce.
NEEDS_INSTRUMENTATION: dict[str, str] = {
    "component.latency_component":
        "needs per-stage timings; return {'timings': {'retrieve': 0.1, ...}} "
        "from call_app to measure it",
    "application.time_to_first_token":
        "needs a streaming call; time the first chunk and return "
        "{'ttft': seconds} from call_app",
    "application.cost_per_query":
        "needs the cost of the call; return {'cost': usd} from call_app",
    "component.parameter_correctness":
        "needs the arguments your agent passed to each tool; return "
        "{'tools': [{'name': ..., 'args': {...}}]} from call_app, and fill in "
        "EXPECTED_TOOL_ARGS",
    "workflow.termination":
        "needs the agent's iteration count; return {'steps': n} from call_app",
    "component.schema_validity":
        "needs the parsed object; return {'structured': obj} from call_app",
    "component.required_fields":
        "needs the parsed object and REQUIRED_FIELDS filled in in harness.py",
    "component.enum_membership":
        "needs the parsed object and ALLOWED_VALUES filled in in harness.py",
}


def _brief(reason: str) -> str:
    """The instrumentation note, trimmed to fit a table cell."""
    return reason.split(";")[0].strip()


# ---------------------------------------------------------------------------
# harness
# ---------------------------------------------------------------------------

HARNESS = '''{banner}
"""Shared plumbing: one place that knows how to call your application.

Every generated eval imports from here, so this is the only file that has to
change when your entry point moves. It was written against what the scanner
found; if the call below is wrong, fix it here once.

Discovered entry point{plural}:
{discovered}
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

# DeepEval's progress output contains emoji, and the Windows console defaults to
# cp1252, which cannot encode them -- the run dies in the reporter after every
# API call has already been paid for. Reconfiguring here rather than asking the
# user to set PYTHONIOENCODING, because they would only find out by losing a run.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).parent
GOLDENS = HERE / "goldens"

# The judge. Every model-graded metric uses this one model, so scores stay
# comparable across the suite and an upgrade is a single edit.
#
# Resolved rather than passed through: DeepEval accepts a bare string only for
# OpenAI, and silently treats "claude-sonnet-4-5" as an OpenAI model name --
# which fails at the first call with an error about the wrong provider.
JUDGE_SPEC = os.environ.get("LIVINGEVAL_JUDGE", "{judge}")


def _resolve_judge(spec: str):
    provider, _, name = spec.partition(":")
    if not name:                      # a bare model name means OpenAI
        return spec
    if provider == "openai":
        return name
    if provider == "anthropic":
        from deepeval.models import AnthropicModel
        return AnthropicModel(model=name, temperature=0)
    if provider == "ollama":
        from deepeval.models import OllamaModel
        return OllamaModel(model=name, temperature=0)
    raise ValueError(
        f"unknown judge {{spec!r}}. Use openai:<model>, anthropic:<model> or "
        f"ollama:<model>.")


JUDGE = _resolve_judge(JUDGE_SPEC)

# Per-metric pass marks. These are starting points, not measurements: run
# `livingeval baseline` to replace them with values taken from your own system.
THRESHOLDS = {thresholds}

# Judge concurrency. Raise if your provider tolerates it and you want the suite
# to finish sooner; lower if you see timeouts. The defaults are chosen to
# complete on a standard rate limit rather than to be quick.
MAX_CONCURRENT = int(os.environ.get("LIVINGEVAL_MAX_CONCURRENT", "4"))
THROTTLE_SECONDS = float(os.environ.get("LIVINGEVAL_THROTTLE", "0.5"))


# Why a metric has no cases, keyed by metric. A skipped set that leaves no
# trace is indistinguishable from a metric nobody planned, and the second is
# fine while the first is a hole in the suite.
SKIPPED: dict = {{}}


def load_cases(metric_keys: list[str]) -> dict:
    """Golden sets for these metrics. Incomplete sets are reported, not scored."""
    out = {{}}
    for key in metric_keys:
        path = GOLDENS / (key.replace(".", "_") + ".json")
        if not path.exists():
            SKIPPED[key] = "no golden set was written for this metric"
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        if not data.get("complete", False):
            n = len(data["cases"])
            print(f"  ~ {{key}}: golden set incomplete, skipping "
                  f"({{n}} cases awaiting answers)")
            SKIPPED[key] = (f"{{n}} cases in goldens/{{path.name}} are still "
                            f"awaiting the reference answers only you can write")
            continue
        out[key] = data["cases"]
    return out


{target}


def local_metric(key: str):
    """A metric read off the calls rather than judged. `measure_telemetry`
    below computes the ones it can and names the ones it cannot."""
    return {{"__local__": key}}


# What the harness can read off a run without being told anything else, and
# what it cannot. A metric it cannot measure is *named*, not dropped: a planned
# metric that quietly produces no number is how a suite ends up reporting on
# whatever was convenient instead of on what matters. Anything listed here as
# unmeasured becomes BLIND at the gate rather than absent from it.
UNMEASURABLE = {unmeasurable}

# Structured-output expectations. The scanner can see that your code asks for a
# schema, but not which fields are required or which values are legal -- those
# live in a class it does not import. Fill these in and the two metrics below
# start measuring; leave them and they report as unmeasured rather than
# passing vacuously.
REQUIRED_FIELDS: list[str] = {required_fields}
ALLOWED_VALUES: dict = {{}}     # {{"field": ["label_a", "label_b"]}}


def _normalise(text: str) -> str:
    return " ".join(str(text).lower().split()).strip(" .!?")


def measure_telemetry(keys: list, calls: list, cases: dict) -> tuple:
    """Scores read off the calls themselves, and reasons for the ones missing.

    `calls` is one record per distinct input actually sent: latency, whether it
    raised, and whatever optional keys call_app chose to return.
    """
    scores, unmeasured = {{}}, {{}}
    done = [c for c in calls if not c["error"]]
    structured = [c for c in done if c.get("structured") is not None]

    for key in keys:
        name = key.split(".")[-1]

        if key in UNMEASURABLE:
            unmeasured[key] = UNMEASURABLE[key]

        elif name == "error_rate":
            if calls:
                scores[key] = sum(1 for c in calls if c["error"]) / len(calls)
            else:
                unmeasured[key] = "no call was made this run"

        elif name == "cost_per_query":
            costs = [c["cost"] for c in done if c.get("cost") is not None]
            if costs:
                scores[key] = sum(costs) / len(costs)
            else:
                unmeasured[key] = ("call_app did not report a cost; return "
                                   "{{'cost': usd}} from it to measure this")

        elif name == "termination":
            steps = [c["steps"] for c in done if c.get("steps") is not None]
            if steps:
                scores[key] = sum(1 for n in steps if n < MAX_STEPS) / len(steps)
            else:
                unmeasured[key] = ("call_app did not report a step count; return "
                                   "{{'steps': n}} from it to measure whether the "
                                   "loop terminates")

        elif name == "schema_validity":
            if done:
                scores[key] = len(structured) / len(done)
            else:
                unmeasured[key] = "no call completed, so nothing was parsed"

        elif name == "required_fields":
            if not REQUIRED_FIELDS:
                unmeasured[key] = ("REQUIRED_FIELDS is empty in harness.py -- "
                                   "name the fields your schema requires")
            elif structured:
                scores[key] = sum(
                    1 for c in structured
                    if isinstance(c["structured"], dict)
                    and all(f in c["structured"] for f in REQUIRED_FIELDS)
                ) / len(structured)
            else:
                unmeasured[key] = "call_app never returned a parsed object"

        elif name == "enum_membership":
            if not ALLOWED_VALUES:
                unmeasured[key] = ("ALLOWED_VALUES is empty in harness.py -- "
                                   "list the legal labels per field")
            elif structured:
                ok = 0
                for c in structured:
                    obj = c["structured"]
                    ok += isinstance(obj, dict) and all(
                        obj.get(f) in allowed
                        for f, allowed in ALLOWED_VALUES.items() if f in obj)
                scores[key] = ok / len(structured)
            else:
                unmeasured[key] = "call_app never returned a parsed object"

        elif name == "accuracy":
            rows = [r for r in cases.get(key, []) if r.get("expected")]
            answers = {{c["input"]: c["answer"] for c in done}}
            if not rows:
                unmeasured[key] = ("the accuracy set has no confirmed labels yet; "
                                   "fill in goldens/{{}}.json".format(
                                       key.replace(".", "_")))
            else:
                scores[key] = sum(
                    1 for r in rows
                    if _normalise(answers.get(r["input"], "")) ==
                    _normalise(r["expected"])) / len(rows)

        elif name in ("latency_p95", "latency_mean"):
            continue                    # computed from the timings below

        else:
            unmeasured[key] = "no measurement wired for this metric"

    return scores, unmeasured


MAX_STEPS = int(os.environ.get("LIVINGEVAL_MAX_STEPS", "12"))

# Every distinct input sent this run, with what came back. Telemetry is read
# off this at the end rather than per pipeline: latency and error rate are
# properties of the run, and a pipeline holding only telemetry metrics -- the
# operational one -- sends nothing itself. Measured per pipeline it would
# report a confident zero error rate over zero calls.
CALLS: list = []
_SEEN: dict = {{}}


def call_once(question: str) -> dict:
    """`call_app`, cached per distinct input and recorded.

    Cached because the same question appears in several metrics' sets and the
    application is the expensive half of the run; recorded because an
    exception is a result. Letting it propagate would discard every judge call
    already paid for on the cases before it, and error_rate is the metric that
    exists to count exactly this.
    """
    if question in _SEEN:
        return _SEEN[question]
    started = time.perf_counter()
    try:
        result = call_app(question)
        error = None
    except Exception as exc:                                   # noqa: BLE001
        result = {{"answer": "", "context": None}}
        error = f"{{type(exc).__name__}}: {{exc}}"
    _SEEN[question] = result
    CALLS.append({{"input": question, "latency": time.perf_counter() - started,
                  "error": error, "answer": result.get("answer", ""),
                  "structured": result.get("structured"),
                  "steps": result.get("steps"), "cost": result.get("cost")}})
    return result


def finalise(local_keys: list) -> tuple:
    """Telemetry for the whole run, once every pipeline has been through.

    Returns (scores, unmeasured). Called by run_suite, not by a pipeline.
    """
    scores: dict = {{}}
    if not CALLS:
        return scores, {{k: "no call was made this run, so there was nothing to "
                        "measure" for k in local_keys}}
    ordered = sorted(c["latency"] for c in CALLS)
    scores["application.latency_p95"] = ordered[int(len(ordered) * 0.95) - 1]
    scores["application.latency_mean"] = sum(ordered) / len(ordered)
    tele, unmeasured = measure_telemetry(local_keys, CALLS, load_cases(local_keys))
    scores.update(tele)
    failures = [c for c in CALLS if c["error"]]
    if failures:
        print(f"\\n  ! {{len(failures)}}/{{len(CALLS)}} calls raised, e.g. "
              f"{{failures[0]['error'][:140]}}")
    return scores, unmeasured


def run_pipeline(name: str, metrics: list, cases: dict) -> dict:
    """Score one pipeline.

    Returns {{"metrics": {{key: mean}}, "cases": {{key: [per-case rows]}},
    "unmeasured": {{key: reason}}, "local": [key]}}, keyed by registry key
    throughout. Telemetry keys come back under "local" for `finalise` to
    measure once the whole run is done.

    Each metric is evaluated against its own golden set, one metric per call.
    Batching them all over the pooled cases is faster and wrong: an injection
    probe judged for toxicity produces a number, and the number is meaningless.

    The per-case rows are what make the comparison a *test* rather than a
    threshold -- `livingeval gate` runs exact McNemar on the paired pass/fail
    and corrects across the family of metrics.
    """
    from deepeval import evaluate
    from deepeval.evaluate.configs import AsyncConfig, DisplayConfig, ErrorConfig
    from deepeval.test_case import LLMTestCase

    scores: dict[str, float] = {{}}
    rows: dict[str, list[dict]] = {{}}
    local_keys = [k for k, m in metrics if isinstance(m, dict)]

    for key, metric in metrics:
        if isinstance(metric, dict):          # measured off the calls, below
            continue
        case_rows = cases.get(key)
        if not case_rows:
            continue

        test_cases, ids = [], []
        for row in case_rows:
            cached = call_once(row["input"])
            ids.append(row["id"])
            test_cases.append(LLMTestCase(
                input=row["input"],
                actual_output=cached.get("answer", ""),
                retrieval_context=cached.get("context"),
                expected_output=row.get("expected"),
            ))

        report = evaluate(
            test_cases=test_cases, metrics=[metric],
            # DeepEval fans out every (case x metric) pair at once, which any
            # provider rate-limits into timeouts -- after you have paid for the
            # calls that did land. Capped so a first run finishes.
            async_config=AsyncConfig(max_concurrent=MAX_CONCURRENT,
                                     throttle_value=THROTTLE_SECONDS),
            # One metric erroring should not discard the whole run. A missing
            # score surfaces in `gate` as a metric present in only one run.
            error_config=ErrorConfig(ignore_errors=True),
            display_config=DisplayConfig(show_indicator=False, print_results=False))

        collected = []
        for case_id, result in zip(ids, getattr(report, "test_results", [])):
            for data in getattr(result, "metrics_data", []):
                collected.append({{
                    "id": case_id,
                    "score": data.score,
                    "passed": bool(data.success),
                    "reason": getattr(data, "reason", None),
                }})
        if collected:
            rows[key] = collected
            valid = [c["score"] for c in collected if c["score"] is not None]
            if valid:
                scores[key] = sum(valid) / len(valid)

    unmeasured: dict = {{}}
    for key, metric in metrics:
        if key in scores or key in local_keys:
            continue
        unmeasured[key] = SKIPPED.get(
            key, "the metric ran but returned no score; see the run output")
    return {{"metrics": scores, "cases": rows, "unmeasured": unmeasured,
            "local": local_keys}}
'''

TARGET_KNOWN = '''def call_app(question: str) -> dict:
    """Call the application under test.

    Returns {{"answer": str, ...}}. Every other key is optional and turns on a
    metric that cannot be measured without it:

        context     list[str]  what the grounding metrics score against --
                               without it faithfulness and contextual relevance
                               have nothing to check the answer against
        structured  dict       the parsed object, for the schema metrics
        steps       int        agent loop iterations, for termination
        cost        float      USD for the call, for cost_per_query

    If your function already returns a dict with these names they are picked up
    as they are.
    """
    from {module} import {function}

    result = {function}({call_args})
    if isinstance(result, dict):
        out = dict(result)
        out["answer"] = result.get("answer", "")
        return out
    return {{"answer": str(result), "context": None}}
'''

TARGET_UNKNOWN = '''def call_app(question: str) -> dict:
    """Call the application under test.

    The scanner could not work out a safe way to invoke your code, so this is
    yours to write. Returning a fake value here would produce a suite that runs
    green against nothing, which is worse than one that refuses to run.

    Return {{"answer": str, "context": list[str] | None}}. Optional keys
    "structured", "steps" and "cost" turn on the schema, termination and cost
    metrics respectively.
    """
    raise NotImplementedError(
        "Wire livingeval to your application: edit call_app() in this file. "
        "The scanner found these entry points:\\n{hints}"
    )
'''


def _required_fields_hint(sites: list) -> str:
    """A seed for REQUIRED_FIELDS, and a comment naming what it came from.

    Static analysis sees that a schema is asked for and how many fields it has,
    not what they are called -- those are attributes of a class in a module the
    scanner does not import. Rather than guess names that will silently never
    match, this leaves the list empty and says which schema to read.
    """
    shapes: dict[str, tuple[int, bool]] = {}
    for site in sites:
        shapes.update(site.evidence.schema_shapes)
    if not shapes:
        return "[]"
    named = ", ".join(f"{n} ({c} fields)" for n, (c, _) in sorted(shapes.items()))
    return f"[]     # schemas found: {named}"


def _harness(plan: Plan, judge: str) -> str:
    sites = plan.sites
    discovered = "\n".join(
        f"  {s.path.as_posix()}:{s.line}  {s.function}()  [{s.archetype}]"
        for s in sites
    ) or "  (none)"

    primary = next((s for s in sites if s.evidence.retrieval), sites[0] if sites else None)
    if primary and primary.function not in {"<module>", "__init__"}:
        module = ".".join(primary.path.with_suffix("").parts).lstrip(".")
        target = TARGET_KNOWN.format(module=module, function=primary.function,
                                     call_args="question")
    else:
        hints = "\\n".join(f"  {s.path}:{s.line} {s.function}()" for s in sites)
        target = TARGET_UNKNOWN.format(hints=hints or "  (none found)")

    thresholds = "{\n" + "".join(
        f'    "{m.key}": {0.3 if not m.higher_is_better else 0.7},\n'
        for p in plan.pipelines for m in p.metrics
    ) + "}"

    # Only the ones with no fallback measurement at all. schema_validity and
    # the rest are computed when call_app supplies the data and report
    # themselves unmeasured when it does not, so listing them here would
    # give up on them before the run.
    hard = {k: v for k, v in NEEDS_INSTRUMENTATION.items()
            if k in ("component.latency_component",
                     "application.time_to_first_token",
                     "component.parameter_correctness")}
    unmeasurable = ("{\n" + "".join(
        f'    "{k}":\n        {v!r},\n' for k, v in sorted(hard.items())) + "}")

    return HARNESS.format(
        banner=BANNER, judge=judge, thresholds=thresholds, target=target,
        discovered=discovered, plural="s" if len(sites) != 1 else "",
        required_fields=_required_fields_hint(sites),
        unmeasurable=unmeasurable)


# ---------------------------------------------------------------------------
# registry, runner, explanation
# ---------------------------------------------------------------------------

REGISTRY = '''{banner}
"""Per-metric direction and noise tolerance.

Regression testing needs both. Direction, because a drop in toxicity is an
improvement and a drop in faithfulness is not -- getting this backwards reports
every safety fix as a regression. Noise tolerance, because these scores are
produced by a probabilistic judge and move by a point or two between identical
runs.

The tolerances below are estimates. `livingeval baseline` runs the suite
repeatedly against an unchanged system and replaces them with the spread it
actually measures, which is the only honest source for this number.

livingeval's gate does not stop at the tolerance -- it runs a paired test and
reports a p-value, and separately asks whether the suite had the power to detect
the regression at all. The tolerance here is what the plain comparison uses.
"""

REGISTRY = {registry}
'''

RUNNER = '''{banner}
"""Run every eval and write one result file.

First run writes `baseline.json`. Subsequent runs write `candidate.json`, which
`livingeval gate` compares against the baseline.

    python -m livingeval_evals.run_suite            # run everything
    python -m livingeval_evals.run_suite --only safety
"""

from __future__ import annotations

import argparse
import importlib
import json
import time
from pathlib import Path

HERE = Path(__file__).parent
PIPELINES = {pipelines!r}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", help="substring filter over pipeline names")
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    selected = [p for p in PIPELINES if not args.only or args.only in p]
    started = time.time()
    metrics: dict = {{}}
    cases: dict = {{}}
    unmeasured: dict = {{}}
    local: list = []
    for name in selected:
        print(f"-> {{name}}")
        module = importlib.import_module(f"livingeval_evals.{{name}}")
        # Each pipeline returns an envelope, not a flat score map. Merging the
        # envelope itself would leave a file with two keys in it and every
        # score but the last pipeline's thrown away.
        result = module.run()
        metrics.update(result.get("metrics", {{}}))
        cases.update(result.get("cases", {{}}))
        unmeasured.update(result.get("unmeasured", {{}}))
        local += [k for k in result.get("local", []) if k not in local]

    # Latency, cost and error rate belong to the run, not to whichever pipeline
    # happens to list them -- the operational pipeline sends no cases of its own.
    from livingeval_evals.harness import finalise
    telemetry, missing = finalise(local)
    metrics.update(telemetry)
    unmeasured.update({{k: v for k, v in missing.items() if k not in metrics}})

    out = args.out or (HERE / ("baseline.json" if not (HERE / "baseline.json").exists()
                               else "candidate.json"))
    out.write_text(json.dumps({{
        "metrics": metrics,
        "cases": cases,
        "unmeasured": unmeasured,
        "pipelines": selected,
        "seconds": round(time.time() - started, 1),
    }}, indent=2), encoding="utf-8")
    print(f"\\nwrote {{out.name}}  ({{len(metrics)}} metrics, "
          f"{{time.time() - started:.0f}}s)")
    if unmeasured:
        print(f"\\n{{len(unmeasured)}} planned metric(s) produced no number. "
              f"`livingeval gate` reports these BLIND rather than passing them:")
        for key, reason in sorted(unmeasured.items()):
            print(f"  ~ {{key}}: {{reason}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''


def _explanation(plan: Plan, goldens: dict[str, GoldenSet]) -> str:
    lines = [
        "# Why this suite looks like this", "",
        plan.summary(), "",
        "Generated by `livingeval init`. Every choice below is explained, because "
        "you should be able to disagree with any of them.", "",
        "## What was found", "",
        "| file | line | function | classified as | confidence |",
        "|---|---|---|---|---|",
    ]
    for site in plan.sites:
        lines.append(f"| `{site.path}` | {site.line} | `{site.function}()` | "
                     f"{site.archetype} | {site.confidence:.0%} |")
    lines += ["", "The classification decides which metrics apply, so it is worth "
                  "checking. Reasons given:", ""]
    for site in plan.sites:
        lines.append(f"- **`{site.function}()`** — " + "; ".join(site.rationale))

    lines += ["", "## The pipelines", ""]
    for pipeline in plan.pipelines:
        lines += [f"### `{pipeline.slug}`", "",
                  f"*{pipeline.level.value} level, {pipeline.risk.value} risk.*", "",
                  "| metric | catches | needs |", "|---|---|---|"]
        for metric in pipeline.metrics:
            if metric.reference is Reference.BASED:
                needs = "a reference answer from you"
            elif metric.key in NEEDS_INSTRUMENTATION:
                needs = _brief(NEEDS_INSTRUMENTATION[metric.key])
            else:
                needs = "nothing — runs now"
            lines.append(f"| `{metric.name}` | {metric.catches} | {needs} |")
        lines.append("")

    lines += ["## The datasets", ""]
    for key, golden in sorted(goldens.items()):
        state = "complete" if golden.complete else "**awaiting your answers**"
        lines += [f"### `{key}` — {state}", "", golden.why, ""]

    lines += [
        "## What livingeval adds once this is running", "",
        "The suite above tells you whether your scores changed. Three questions it "
        "cannot answer on its own, and which `livingeval gate` does:", "",
        "- **Is the change real?** A paired test with a p-value, rather than "
        "comparing against a hand-picked noise threshold.",
        "- **Could this suite have caught the regression?** Detection power, "
        "simulated against a named regression and reported with its false-alarm rate.",
        "- **Does the suite still represent your traffic?** Coverage — the share of "
        "today's traffic sitting near something the suite contains.", "",
        "That last one is why the gate is three-valued. `PASS`, `FAIL`, and `BLIND`: "
        "\"no regression detected, and this suite could not have detected one\" is a "
        "different claim from \"no regression\".",
    ]
    return "\n".join(lines) + "\n"


def emit(plan: Plan, goldens: dict[str, GoldenSet], root: Path,
         judge: str = "openai:gpt-4o-mini", scope: str = "",
         protect: set[str] | None = None) -> Emission:
    """Write the whole suite under `root/livingeval_evals`.

    A package rather than a loose directory, because `run_suite` imports the
    eval modules by name and a plain folder makes that depend on the working
    directory.

    `protect` names files the caller has determined a human edited since they
    were written. They are skipped and reported. Golden sets are always merged
    rather than replaced, whether or not they are protected -- see
    `sync.write_goldens_preserving` for why that one is not negotiable.
    """
    package = root / "livingeval_evals"
    package.mkdir(parents=True, exist_ok=True)
    protect = protect or set()
    written: list[Path] = []
    skipped: list[str] = []
    records: list[FileRecord] = []

    def put(name: str, text: str, kind: str = "eval") -> None:
        if name in protect:
            skipped.append(name)
            return
        path = package / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
        records.append(FileRecord(path=name, written=digest(text), kind=kind))

    put("__init__.py", f'{BANNER}\n"""Generated eval suite. See WHY.md."""\n')
    put("harness.py", _harness(plan, judge))

    for pipeline in plan.pipelines:
        put(f"{pipeline.slug}.py", _eval_file(pipeline, judge))

    registry = {
        m.key: {"direction": "higher" if m.higher_is_better else "lower",
                "noise": m.noise_hint,
                # False until `livingeval baseline` measures the real spread.
                # The gate returns BLIND rather than PASS while this is False,
                # because comparing against a guess is not evidence of stability.
                "measured": False,
                "risk": m.risk.value,
                "catches": m.catches}
        for p in plan.pipelines for m in p.metrics
    }
    put("metric_registry.py", REGISTRY.format(
        banner=BANNER, registry=_pretty(registry)), "registry")
    put("run_suite.py", RUNNER.format(
        banner=BANNER, pipelines=[p.slug for p in plan.pipelines]), "eval")
    put("WHY.md", _explanation(plan, goldens), "doc")

    # Golden sets go through the merge path unconditionally. A dataset somebody
    # spent an afternoon labelling must survive every regeneration, and making
    # that depend on a flag is how it eventually does not.
    preserved = write_goldens_preserving(package, goldens)
    golden_paths = sorted((package / "goldens").glob("*.json"))

    Manifest(
        generated_at=time.time(), judge=judge, scope=scope,
        sites=[SiteRecord(ident=s.ident, path=str(s.path), function=s.function,
                          provider=s.provider, archetype=s.archetype,
                          fingerprint=site_digest(s), line=s.line)
               for s in plan.sites],
        files=records,
        goldens={k: {"complete": g.complete, "cases": len(g.cases)}
                 for k, g in goldens.items()},
        metrics=sorted({m.key for p in plan.pipelines for m in p.metrics}),
    ).save(package)

    return Emission(
        files=written, goldens=golden_paths,
        runnable=plan.runnable_count, blocked=plan.blocked_count,
        preserved=preserved, skipped=skipped)


def _pretty(mapping: dict) -> str:
    import json
    return json.dumps(mapping, indent=4).replace(": true", ": True").replace(
        ": false", ": False").replace(": null", ": None")
